apiVersion: v1
kind: Service
metadata:
  name: edureka-proj-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: edureka-proj-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080